"use client";
import { useEffect,useMemo,useState } from "react";

export type DocumentScope={type:"entire"|"sections"|"pages";sectionIds?:string[];pageStart?:number;pageEnd?:number};
type IndexedSection={id:string;parent_id:string|null;level:number;title:string;page_start:number;page_end:number;confidence:number|string;source:string};
export function DocumentScopePicker({documentId,pageCount,value,onChange,compact=false}:{documentId:string;pageCount?:number|null;value:DocumentScope;onChange:(scope:DocumentScope)=>void;compact?:boolean}){
  const[sections,setSections]=useState<IndexedSection[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(!documentId){setSections([]);return}setLoading(true);setError("");fetch(`/api/documents/index?documentId=${encodeURIComponent(documentId)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load index");setSections(data.sections||[])}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load index")).finally(()=>setLoading(false))},[documentId]);
  const selected=new Set(value.sectionIds||[]),label=useMemo(()=>value.type==="entire"?"Entire document":value.type==="pages"?`Pages ${value.pageStart}–${value.pageEnd}`:`${selected.size} selected section${selected.size===1?"":"s"}`,[value,selected.size]);
  function toggle(id:string){const next=new Set(selected);if(next.has(id))next.delete(id);else next.add(id);onChange({type:"sections",sectionIds:[...next]})}
  return <div className={`scope-picker ${compact?"compact":""}`}><div className="scope-head"><b>AI scope</b><span>{label}</span></div><div className="scope-tabs"><button className={value.type==="sections"?"active":""} onClick={()=>onChange({type:"sections",sectionIds:value.sectionIds||[]})}>Index</button><button className={value.type==="pages"?"active":""} onClick={()=>onChange({type:"pages",pageStart:value.pageStart||1,pageEnd:value.pageEnd||Math.min(5,pageCount||5)})}>Pages</button><button className={value.type==="entire"?"active":""} onClick={()=>onChange({type:"entire"})}>Entire document</button></div>
  {loading&&<small>Loading document index…</small>}{error&&<small className="scope-error">{error}</small>}
  {value.type==="sections"&&<div className="scope-tree">{sections.map(section=><label key={section.id} style={{paddingLeft:`${Math.max(0,section.level-1)*18+8}px`}}><input type="checkbox" checked={selected.has(section.id)} onChange={()=>toggle(section.id)}/><span><b>{section.title}</b><small>pp. {section.page_start}{section.page_end!==section.page_start?`–${section.page_end}`:""}</small></span></label>)}{!loading&&!sections.length&&<small>No indexed sections are available yet.</small>}</div>}
  {value.type==="pages"&&<div className="page-scope"><label>From page<input type="number" min="1" max={pageCount||1} value={value.pageStart||1} onChange={event=>onChange({...value,pageStart:Number(event.target.value)})}/></label><label>To page<input type="number" min="1" max={pageCount||1} value={value.pageEnd||1} onChange={event=>onChange({...value,pageEnd:Number(event.target.value)})}/></label></div>}
  {value.type==="entire"&&<small>StudyOS will process the index section-by-section and synthesize the result. The PDF file itself is never attached to Gemini.</small>}</div>
}
